#' Default color scheme for NPCA results
#'
#' Applies a default color scheme for displaying the results of NPCA generated by \code{\link{NP}}
#'
#' @export
#' @param NP_Results A character vector. Must be one of the columns generated by \code{\link{NP}} ending in "_Res"
#' @return Returns a character vector of length \code{NP_Results} containing hexadecimal color codes
#' @seealso See \code{\link{NP}}
#' @author Eli Weaverdyck \email{eweaverdyck@@gmail.com}
#' @examples NP_colors(
#' NP(chron = chron,
#'   chron_ID = "Survey_Uni",
#'   periods = c("Clas", "Hell", "Cl_He", "ER", "MR", "LR", "LR_EB"),
#'   tracts = tracts,
#'   tracts_ID = "UnitID",
#'   swl = IDW_nnear(tracts = tracts, tracts_ID = "UnitID", n = 8),
#'   perms = 100,
#'   cut = 0.05)[["Clas_Res"]])

NP_colors<-function(NP_Results){
  checkmate::assert_subset(unique(NP_Results), c("Absent, Moderate NP", "Present, Moderate NP", "Present, Low NP", "Present, High NP", "Absent, Low NP", "Absent, High NP"))

  colors.df<-as.data.frame(matrix(nrow=length(NP_Results),ncol=2))
  colnames(colors.df)<-c("result","color")
  colors.df$result<-NP_Results
  colors.df$color[colors.df$result == "Present, High NP"] <- "#e60000"
  colors.df$color[colors.df$result == "Present, Low NP"] <- "#feff73"
  colors.df$color[colors.df$result == "Present, Moderate NP"] <- "#ffaa01"
  colors.df$color[colors.df$result == "Absent, High NP"] <- "#febebe"
  colors.df$color[colors.df$result == "Absent, Low NP"] <- "#ddd2ff"
  colors.df$color[colors.df$result == "Absent, Moderate NP"] <- "#b5d69f"
  colors<-colors.df$color
  return(colors)
}
