#' Survey units.
#'
#' A data set containing the geometry for 248 units surveyed in the 2015
#' season of the Molyvoti, Thrace Archaeology Project (MTAP).
#'
#' @format An \code{sf} object with 248 rows and one variable:
#' \describe{
#' \item{UnitID}{Unique Identifier for each unit generated by the MTAP}
#' }
#'
#' @source Molyvoti, Thrace, Archaeology Project
#'
"tracts"
